### ISSUE TITLE
language-6809 doesn't install (MacOS X Big Sur/Intel/Atom 1.53.0)

### ISSUE THREAD

**Issue by drchrispinnock** [georgjz/language-6809#15]
> tree-sitter-6809@0.1.4 install /private/var/folders/l8/1tsf14x9677_lfs5lxxr9dn00000gn/T/apm-install-dir-2021012-34265-2cattk.tv8jp/node_modules/language-6809/node_modules/tree-sitter-6809
> node-gyp rebuild

  CC(target) Release/obj.target/tree_sitter_asm6809_binding/src/parser.o
  CXX(target) Release/obj.target/tree_sitter_asm6809_binding/src/binding.o

../src/binding.cc:13:11: error: no template named 'Handle'
void Init(Handle<Object> exports, Handle<Object> module) {
          ^
../src/binding.cc:13:35: error: no template named 'Handle'
void Init(Handle<Object> exports, Handle<Object> module) {
                                  ^
../src/binding.cc:18:50: error: too few arguments to function call, single argument 'context' was not specified
  Local<Function> constructor = tpl->GetFunction();
                                ~~~~~~~~~~~~~~~~ ^
/Users/chris/.atom/.node-gyp/Library/Caches/node-gyp/6.1.12/include/node/v8.h:5891:3: note: 'GetFunction' declared here
  V8_WARN_UNUSED_RESULT MaybeLocal<Function> GetFunction(
  ^
/Users/chris/.atom/.node-gyp/Library/Caches/node-gyp/6.1.12/include/node/v8config.h:351:31: note: expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
../src/binding.cc:22:13: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
  instance->Set(Nan::New("name").ToLocalChecked(), Nan::New("asm6809").ToLocalChecked());
            ^
/Users/chris/.atom/.node-gyp/Library/Caches/node-gyp/6.1.12/include/node/v8.h:3330:3: note: 'Set' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/chris/.atom/.node-gyp/Library/Caches/node-gyp/6.1.12/include/node/v8config.h:311:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
1 warning and 3 errors generated.
make: *** [Release/obj.target/tree_sitter_asm6809_binding/src/binding.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:200:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Darwin 20.2.0
gyp ERR! command "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /private/var/folders/l8/1tsf14x9677_lfs5lxxr9dn00000gn/T/apm-install-dir-2021012-34265-2cattk.tv8jp/node_modules/language-6809/node_modules/tree-sitter-6809
gyp ERR! node -v v12.4.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open '/private/var/folders/l8/1tsf14x9677_lfs5lxxr9dn00000gn/T/apm-install-dir-2021012-34265-2cattk.tv8jp/package.json'
npm WARN apm-install-dir-2021012-34265-2cattk.tv8jp No description
npm WARN apm-install-dir-2021012-34265-2cattk.tv8jp No repository field.
npm WARN apm-install-dir-2021012-34265-2cattk.tv8jp No README data
npm WARN apm-install-dir-2021012-34265-2cattk.tv8jp No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tree-sitter-6809@0.1.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the tree-sitter-6809@0.1.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/chris/.atom/.apm/_logs/2021-01-12T14_47_10_230Z-debug.log

**Comment by drchrispinnock** [comment]
It's entirely possibly this is due to the bison supplied with Big Sur.

If I rebuild grammar.h with the latest bison, it all works very nicely.
